name: mkdocs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: ğŸ” Checkout the repository
        uses: actions/checkout@v2

      - name: â›­ Set up Python ${{ matrix.python-version }}...
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: â¬†ï¸ Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip
          python3 -m pip -V
      
      - name: â›­ Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"
      
      - name: â›­ Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: â›­ Install requirements
        run: python3 -m pip install -r ./requirements.txt
      
      - name: ğŸ“ Build docs
        run: mkdocs build
        
      - name: ğŸš€ Deploy 
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
